### PR TITLE
Deprecate

### PR DESCRIPTION
**Pull request by aptalca**
[linuxserverurl]: https://linuxserver.io
[linuxserver.io][linuxserverurl]

### CODE REVIEW

**Comment by aptalca** [comment]
jenkins test this please

**Comment by aptalca** [comment]
jenkins test this please

**Comment by thelamer** [comment]
Jenkins test this please, but make it build this time

**Comment by aptalca** [comment]
That's the dreaded "Cannot retrieve Git metadata for the build" error. The only thing that fixes it is a new branch and PR. Ugh!

**Pull request closed without merging**
